config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "cocktails#index"
  resources :cocktails do
    resources :doses, only: [:index, :show, :create, :new]
    end
    resources :doses, only: [:index, :show, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :ingredients, through: :doses
  has_many :doses, dependent: :destroy
  validates :name, uniqueness: true, presence: true

  mount_uploader :photo, PhotoUploader
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, presence: true
  validates :cocktail, presence: true, uniqueness: { scope: :ingredient}
  validates :ingredient, presence: true, uniqueness: {scope: :cocktail}
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

  before_action :find_cocktail, only: [:show, :destroy]

  def index
    @cocktails = Cocktail.all
  end

  def show
    @ingredients = Ingredient.order("name asc")
    @dose = Dose.new
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @cocktail.destroy
    redirect_to cocktails_path
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end

  def find_cocktail
    @cocktail = Cocktail.find(params[:id])
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @ingredient = Ingredient.all
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @dose.cocktail = Cocktail.find(params[:cocktail_id])
    if @dose.save
    redirect_to cocktail_path(@dose.cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @cocktail = @dose.cocktail
    @dose.destroy
    redirect_to cocktail_path(@cocktail)
  end

    private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end

end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/cocktails/_form.html.erb
<%= simple_form_for(cocktail) do |f| %>
  <% if cocktail.errors.any? %>
    <div class="errors-container">
      <ul>
        <% cocktail.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.input :name, class: 'form-control'%>
  </div>
  <div class="form-group">
    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>
  </div>
  <%= f.submit class: 'btn btn-outline-primary' %>
  <%= f.button :button, 'Cancel', type: :reset, class: 'btn btn-outline-dark' %>

<% end %>

app/views/cocktails/edit.html.erb
<div class="container">
  <div class="header">
    <ul class="nav nav-tabs" id="myTab" role="tablist">
      <li class="nav-item">
        <%= link_to "List", cocktails_path, class: "nav-link active" %>
      </li>
      <li class="nav-item">
        <%= link_to "Add Cocktails", new_cocktail_path, class: "nav-link active" %>
      </li>
      <li class="nav-item">
        <%= link_to "Edit", edit_cocktail_path(@cocktails), class: "nav-link active" %>
      </li>
    </ul>
    <div class="tab-content" id="myTabContent">
      <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="list-tab"><div class="new_flat col-6">
        <h2>Edit Cocktail</h2>
        <%= render 'form', cocktail: @cocktail %>
      </div></div>
      <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="add-new-tab">

      </div>
      <div class="tab-pane fade" id="contact" role="tabpanel" aria-labelledby="edit-tab">...</div>
    </div>
  </div>
  <div class="wrapper">

  </div>
</div>

app/views/cocktails/index.html.erb
<div class="container">
  <div class="header mt-4">
    <ul class="nav nav-tabs" id="myTab" role="tablist">
      <li class="nav-item">
        <%= link_to "List", cocktails_path, class: "nav-link active" %>
      </li>
      <li class="nav-item">
        <%= link_to "Add Cocktails", new_cocktail_path, class: "nav-link active" %>
      </li>
    </ul>
    <div class="tab-content" id="myTabContent">
      <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
        <h2 class="mt-4">Cockttail list (<%= @cocktails.count %>)</h2>
        <div class="row mt-3">
          <% @cocktails.each do |cocktail| %>
          <div class="col-sm-4">
            <div class="card mt-3">
              <%#if cocktail.photo.present?%>
              <%= cl_image_tag cocktail.photo, height: 200, width: 250, crop: :fill, class: "card-img-top" %>
              <%#end%>
              <div class="card-body">
              <h5 class="card-title"><%= link_to cocktail.name, cocktail_path(cocktail)%></h5>
              </div>
              <div class="d-flex justify-content-around py-2 border-top">
                <%= link_to raw('<i class="fas fa-trash"></i>'), cocktail_path(cocktail), method: :delete, data: { confirm: "are you deleting my lovely #{cocktail.name} cocktail?" }%>
                <%= link_to raw('<i class="fas fa-cocktail"></i>'), cocktail_path(cocktail)%>
              </div>
            </div>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/cocktails/new.html.erb
<div class="container">
  <div class="header mt-4">
    <ul class="nav nav-tabs" id="myTab" role="tablist">
      <li class="nav-item">
        <%= link_to "List", cocktails_path, class: "nav-link active" %>
      </li>
      <li class="nav-item">
        <%= link_to "Add Cocktails", new_cocktail_path, class: "nav-link active" %>
      </li>
    </ul>
    <div class="tab-content" id="myTabContent">
      <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="list-tab">
        <div class="new_flat col-6">
        <h2 class="mt-3">Add New Cocktail</h2>
        <%= render 'form', cocktail: @cocktail %>
      </div></div>
    </div>
  </div>
</div>

app/views/cocktails/show.html.erb
<div class="container">
  <div class="header mt-4">
    <ul class="nav nav-tabs" id="myTab" role="tablist">
      <li class="nav-item">
        <%= link_to "List", cocktails_path, class: "nav-link active" %>
      </li>
      <li class="nav-item">
        <%= link_to "Add Cocktails", new_cocktail_path, class: "nav-link active" %>
      </li>
    </ul>
    <div class="tab-content" id="myTabContent">
      <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
        <h2 class="mt-3"><%= @cocktail.name %></h2>
        <%= cl_image_tag cocktail.photo, height: 200, width: 250, crop: :fill, class: "card-img-top my-3" %>
        <h5>Ingredients</h5>
        <ul class="list-group list-group-flush col-sm-6">
          <% @cocktail.doses.each do |d|  %>
          <li class="list-group-item"><%= d.ingredient.name %> : <%= d.description %> | <%= link_to raw('<i class="fas fa-trash"></i>'), dose_path(d), method: :delete, data: { confirm: "Are you taking out ingredient?" }  %></li>
          <% end %>
        </ul>
         <%= simple_form_for [@cocktail, @dose] do |f| %>
        <div class="form-group col-sm-6">
          <strong>Add Ingredient:</strong>
          <%= f.input :ingredient_id, label: 'Select from the list', collection: @ingredients, class: 'form-control' %>
        </div>
        <div class="form-group col-sm-6">
          <%= f.input :description, label: 'Tell Marty how to' , class: 'form-control'  %>
        </div>
          <%= f.submit class: 'btn btn-outline-primary' %>
          <%= f.button :button, 'Cancel', type: :reset, class: 'btn btn-outline-success' %>
          <%= link_to 'View Cocktails List', cocktails_path, class: 'btn btn-outline-dark' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/doses/new.html.erb
<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.input :ingredient_id, collection: @ingredients %>
  <%= f.input :description %>
  <%= f.submit "add dose", class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
    <%= javascript_include_tag "application" %>
    <%= javascript_pack_tag "application" %>
  </body>
</html>